#multiple lnear regression
auto<-read.csv("Auto.csv", na.strings = "?", stringsAsFactors=T )
attach(auto)
View(auto)
cor(mpg,data.frame(cylinders,displacement, horsepower, weight, acceleration, year))
multi.liner<-lm(mpg ~. -name, data=auto)
summary(multi.liner)
par(mfrow=c(2,2))
plot(multi.liner)
multi.linear.inter<-lm(mpg ~.-name + acceleration:displacement, data=auto)
summary(multi.linear.inter)
dev.off()
par(mfrow=c(2,2))
plot(multi.linear.inter)
multi.linear.inter2<-lm(mpg ~. -name + displacement:cylinders, data = auto)
summary(multi.linear.inter2)
multi.linear.inter2<-lm(mpg ~. -name + displacement:cylinders + horsepower:cylinders, data = auto)
summary(multi.linear.inter2)
